### ISSUE TITLE
Many Test Failures against Text::Markdown 1.0.26

### ISSUE THREAD

**Issue by klp2** [bobtfish/text-multimarkdown#7] opened 2009-10-04 21:37 UTC
A large number of the tests fail as of today, it looks like all related to <p></p> tags showing up where not expected, and not showing up when they are expected.  A couple of examples are pasted below

Failed test at t/04markdown.t line 14.
          got: 'Foo

 Bar
 '
     expected: '<p>Foo</p>

 <p>Bar</p>
 '

   Failed test at t/04markdown.t line 26.
          got: 'Foo

 Bar
 '
     expected: '<p>Foo</p>

 <p>Bar</p>
 '
   Failed test at t/05options.t line 12.
          got: '<p>[test][] the link!</p>
 '
     expected: '[test][] the link!
 '

   Failed test at t/05options.t line 20.
          got: '<p><a href="http://example.com">test</a> the link!</p>
 '
     expected: '<a href="http://example.com">test</a> the link!
 '

**Comment by dandv** [comment] 2009-10-05 05:36
Thanks for reporting. Caused by an internal API change in Text::Markdown and fixed by commit 86402d0765f97485f2a33fb844c6e59d26f6b538.

**Closed as completed by dandv** 2009-10-05 05:36 UTC

**Comment by bobtfish** [comment] 2009-10-06 07:31
Fixed by new release. Thanks for the bug report

**Comment by klp2** [comment] 2009-10-06 23:19
thanks!
